import {
  TASK_CONTEXT_PACK_SCHEMA,
  TASK_PLAN_SCHEMA,
  TASK_RUN_JOURNAL_SCHEMA,
  TASK_SPEC_SCHEMA,
} from './task-schemas.js';

export const TASK_PROTOCOL_CONTRACT_VERSION = 'BlueprintHelper.TaskProtocolContract.v1';

export const TASK_PROTOCOL_CONTRACT_V1 = {
  schema: TASK_PROTOCOL_CONTRACT_VERSION,
  task_spec_schema: TASK_SPEC_SCHEMA,
  task_plan_schema: TASK_PLAN_SCHEMA,
  context_pack_schema: TASK_CONTEXT_PACK_SCHEMA,
  task_run_journal_schema: TASK_RUN_JOURNAL_SCHEMA,
  agent_facing_tools: [
    'blueprinthelper_get_runtime_profile',
    'blueprinthelper_diagnostics',
    'blueprinthelper_read_task_context',
    'blueprinthelper_preview_task',
    'blueprinthelper_execute_task',
    'blueprinthelper_get_task_result',
  ],
  ownership: {
    agent_writes: [TASK_SPEC_SCHEMA],
    compiler_writes: [TASK_PLAN_SCHEMA],
    runtime_writes: [TASK_RUN_JOURNAL_SCHEMA],
    agent_must_not_write: [TASK_PLAN_SCHEMA],
  },
  task_spec_required_paths: [
    'schema',
    'task_type',
    'target.asset_path',
    'scope_policy.graph_name',
    'scope_policy.allow_modify_user_nodes',
    'behavior.graph_strategy',
    'behavior.entries[] for append_new_owned_graph',
    'behavior.replace for replace_owned_graph',
    'behavior.patches[] for patch_owned_graph',
    'behavior.merges[] for merge_owned_graph',
    'validation.should_compile',
    'validation.should_save',
  ],
  task_plan_required_paths: [
    'schema',
    'task_type',
    'target_assets[]',
    'execution_policy.dry_run_mode',
    'execution_policy.should_compile',
    'execution_policy.should_save',
    'steps[].step_id',
    'steps[].capability',
    'steps[].target.asset_path',
    'steps[].target.graph',
    'steps[].write.strategy',
    'steps[].write.ops[]',
    'steps[].constraints.allow_modify_user_nodes',
    'steps[].constraints.ownership_scope',
  ],
  supported_first_slice: {
    task_type: 'edit_blueprint_graph',
    target_type: 'blueprint',
    graph_strategies: [
      'append_new_owned_graph',
      'replace_owned_graph',
      'patch_owned_graph',
      'merge_owned_graph',
    ],
    entry_types: ['custom_event'],
    statement_kinds: ['call_function', 'set_member_variable'],
    task_plan_capability: 'graph_write',
    task_plan_dependency_capabilities: ['blueprint_signature'],
    runtime_lowering_adapters: [
      'append_blueprint_graph',
      'replace_blueprint_graph',
      'patch_blueprint_graph',
      'merge_blueprint_graph',
    ],
    step_batching: 'append custom_event entries compile signature dependency steps before one graph_write body step; replace/patch/merge compile to one structural op per step',
  },
  supported_second_slice: {
    task_type: 'edit_blueprint_variables',
    target_type: 'blueprint',
    variable_strategies: ['member_variables', 'member_defaults', 'local_variables'],
    agent_semantic_paths: [
      'behavior.variable_strategy',
      'behavior.changes[].kind',
      'behavior.defaults[].name',
      'behavior.defaults[].value',
      'behavior.function_name',
    ],
    forbidden_agent_fields: [
      'steps[].operation',
      'write.ops[].op',
      'adapter_operation',
    ],
    task_plan_capability: 'blueprint_variable',
    compiler_supported_structural_ops: [
      'ensure_member_variable',
      'set_member_variable_properties',
      'remove_member_variable',
      'set_member_default',
      'ensure_local_variable',
      'set_local_variable_properties',
      'remove_local_variable',
    ],
    runtime_supported_structural_ops: [
      'ensure_member_variable',
      'set_member_variable_properties',
      'remove_member_variable',
      'set_member_default',
      'ensure_local_variable',
      'set_local_variable_properties',
      'remove_local_variable',
    ],
    runtime_lowering_pending_ops: [],
    runtime_service_pending_ops: [
      'ensure_local_variable',
      'set_local_variable_properties',
      'remove_local_variable',
    ],
    runtime_lowering_adapters: ['add_blueprint_member_variables', 'blueprint_variable_batch'],
    adapter_dry_run_supported: false,
    max_task_plan_steps: 1,
  },
  supported_composite_slice: {
    task_type: 'create_blueprint_feature',
    target_type: 'blueprint',
    compiler_role: 'decompose semantic feature TaskSpec into existing capability TaskPlan steps',
    supported_sections: [
      'components[]',
      'variables[]',
      'class_settings.implemented_interfaces[]',
      'class_settings.class_defaults',
      'behavior',
      'integration.interface',
    ],
    emitted_taskplan_capabilities: [
      'blueprint_component',
      'blueprint_variable',
      'blueprint_class_settings',
      'blueprint_signature',
      'graph_write',
    ],
    supported_integration_semantics: [
      'integration.interface.interface_asset',
      'integration.interface.function',
      'integration.interface.implementation.call',
      'integration.interface.implementation.body',
    ],
    rejected_semantics: [
      'integration.input',
      'scope_policy.allow_create_assets=true',
    ],
    forbidden_agent_fields: [
      'steps[].operation',
      'write.ops[].op',
      'adapter_operation',
    ],
  },
  supported_p1_slices: [
    {
      task_type: 'create_asset',
      target_type: 'asset',
      asset_strategy: 'ensure_asset',
      agent_semantic_paths: [
        'behavior.asset_strategy=ensure_asset',
        'behavior.asset.collision_policy',
      ],
      forbidden_agent_fields: [
        'behavior.asset_strategy=asset_create',
        'behavior.asset.collision',
        'steps[].operation',
        'write.ops[].op',
      ],
      task_plan_capability: 'asset_factory',
      runtime_supported_structural_ops: ['create_asset'],
      runtime_lowering_adapters: ['create_asset'],
    },
    {
      task_type: 'edit_blueprint_components',
      target_type: 'blueprint',
      component_strategy: 'component_tree',
      change_kinds: ['ensure_component_present', 'configure_component', 'remove_component'],
      agent_semantic_paths: [
        'behavior.component_strategy=component_tree',
        'behavior.changes[].kind',
        'behavior.changes[].name',
      ],
      forbidden_agent_fields: [
        'behavior.changes[].op',
        'steps[].operation',
        'write.ops[].op',
      ],
      task_plan_capability: 'blueprint_component',
      runtime_supported_structural_ops: ['add_component', 'set_component_properties', 'remove_component'],
      runtime_lowering_adapters: ['add_component', 'set_component_properties', 'remove_component'],
    },
    {
      task_type: 'edit_blueprint_class_settings',
      target_type: 'blueprint',
      class_settings_strategy: 'class_settings',
      semantic_groups: ['interfaces.ensure_present', 'interfaces.ensure_absent', 'class_defaults'],
      rejected_semantics: ['parent_class', 'reparent'],
      agent_semantic_paths: [
        'behavior.class_settings_strategy=class_settings',
        'behavior.interfaces.ensure_present[]',
        'behavior.interfaces.ensure_absent[]',
        'behavior.class_defaults[]',
      ],
      forbidden_agent_fields: [
        'behavior.ops[]',
        'steps[].operation',
        'write.ops[].op',
      ],
      task_plan_capability: 'blueprint_class_settings',
      runtime_supported_structural_ops: [
        'add_implemented_interfaces',
        'remove_implemented_interfaces',
        'set_class_default_properties',
      ],
      runtime_lowering_adapters: [
        'add_implemented_interfaces',
        'remove_implemented_interfaces',
        'set_class_default_properties',
      ],
    },
    {
      task_type: 'edit_umg_widget',
      target_type: 'widget_blueprint',
      widget_strategy: 'widget_blueprint_edit',
      change_kinds: ['create_widget', 'update_widget_property', 'delete_widget'],
      rejected_semantics: ['move_widget'],
      agent_semantic_paths: [
        'behavior.widget_strategy=widget_blueprint_edit',
        'behavior.changes[].kind',
        'behavior.changes[].widget_name',
      ],
      forbidden_agent_fields: [
        'behavior.changes[].op',
        'steps[].operation',
        'write.ops[].op',
      ],
      task_plan_capability: 'umg_widget',
      runtime_supported_structural_ops: ['add_widget', 'set_widget_property', 'remove_widget'],
      runtime_lowering_adapters: ['add_widget', 'set_widget_property', 'remove_widget'],
    },
    {
      task_type: 'edit_data_table',
      target_type: 'data_table',
      row_strategy: 'row_edit',
      row_actions: ['add', 'update', 'delete'],
      agent_semantic_paths: [
        'behavior.row_strategy=row_edit',
        'behavior.rows[].action',
      ],
      forbidden_agent_fields: [
        'behavior.rows[].op',
        'steps[].operation',
        'write.ops[].op',
      ],
      task_plan_capability: 'data_table',
      runtime_supported_structural_ops: ['add_row', 'update_row', 'delete_row'],
      runtime_lowering_adapters: ['add_datatable_row', 'update_datatable_row', 'delete_datatable_row'],
    },
  ],
  graph_write_taskplan_ir_contract: {
    ownership: 'compiler_owned_internal_protocol',
    agent_authorship: 'forbidden',
    step_shape: {
      step_id: 'string',
      capability: 'graph_write',
      target_required_paths: [
        'target.asset_path',
        'target.graph',
      ],
      write_required_paths: [
        'write.strategy',
        'write.ops[]',
      ],
      constraints_required_paths: [
        'constraints.allow_modify_user_nodes',
        'constraints.ownership_scope',
      ],
    },
    supported_write_strategies: [
      'owned_graph_edit',
    ],
    supported_structural_ops: [
      'ensure_entry',
      'replace_body',
      'set_pin_default',
      'set_node_comment',
      'set_node_position',
      'insert_flow',
    ],
    runtime_supported_structural_ops: [
      'ensure_entry',
      'replace_body',
      'set_pin_default',
      'set_node_comment',
      'set_node_position',
      'insert_flow',
    ],
    lowering_policy: 'UE Task Runtime lowers structural GraphWrite IR ops to existing capability cluster commands.',
  },
  graph_write_lowering_adapter_contract: {
    ownership: 'runtime_owned_adapter_protocol',
    taskplan_source: 'graph_write_taskplan_ir_contract',
    agent_authorship: 'forbidden',
    operations: [
      {
        operation: 'append_blueprint_graph',
        ue_command: 'append_blueprint_graph',
        target_required_paths: [
          'target.asset_path',
          'target.graph',
        ],
        args_required_paths: [
          'args.nodes[]',
          'args.links[]',
        ],
        args_optional_paths: [
          'args.feature_name',
        ],
        dry_run_bridge_path: 'root.dry_run',
      },
      {
        operation: 'replace_blueprint_graph',
        ue_command: 'replace_blueprint_graph',
        target_required_paths: [
          'target.asset_path',
          'target.graph',
          'target.replace_scope',
        ],
        args_required_paths: [
          'args.selector',
          'args.replacement.nodes[]',
          'args.replacement.links[]',
        ],
        args_optional_paths: [
          'args.options.strict',
          'args.options.preserve_layout',
        ],
        dry_run_bridge_path: 'options.dry_run',
      },
      {
        operation: 'patch_blueprint_graph',
        ue_command: 'patch_blueprint_graph',
        target_required_paths: [
          'target.asset_path',
          'target.graph',
          'target.patch_scope',
        ],
        args_required_paths: [
          'args.patch_type',
          'args.patched_ref',
          'args.patch',
        ],
        args_optional_paths: [
          'args.expected_old_state',
        ],
        dry_run_bridge_path: 'root.dry_run',
      },
      {
        operation: 'merge_blueprint_graph',
        ue_command: 'merge_blueprint_graph',
        target_required_paths: [
          'target.asset_path',
          'target.graph',
          'target.merge_scope',
          'target.insert_strategy',
        ],
        args_required_paths: [
          'args.anchor',
          'args.inserted',
        ],
        args_optional_paths: [
          'args.sequence_order[]',
        ],
        dry_run_bridge_path: 'root.dry_run',
      },
    ],
  },
  blueprint_variable_taskplan_ir_contract: {
    ownership: 'compiler_owned_internal_protocol',
    agent_authorship: 'forbidden',
    step_shape: {
      step_id: 'string',
      capability: 'blueprint_variable',
      target_required_paths: [
        'target.asset_path',
      ],
      write_required_paths: [
        'write.strategy',
        'write.ops[]',
      ],
      constraints_required_paths: [
        'constraints.allow_remove_referenced_variables',
      ],
    },
    supported_write_strategies: [
      'member_variables',
      'member_defaults',
      'local_variables',
    ],
    compiler_supported_structural_ops: [
      'ensure_member_variable',
      'set_member_variable_properties',
      'remove_member_variable',
      'set_member_default',
      'ensure_local_variable',
      'set_local_variable_properties',
      'remove_local_variable',
    ],
    runtime_supported_structural_ops: [
      'ensure_member_variable',
      'set_member_variable_properties',
      'remove_member_variable',
      'set_member_default',
      'ensure_local_variable',
      'set_local_variable_properties',
      'remove_local_variable',
    ],
    runtime_lowering_pending_ops: [],
    runtime_service_pending_ops: [
      'ensure_local_variable',
      'set_local_variable_properties',
      'remove_local_variable',
    ],
    lowering_policy: 'UE Task Runtime lowers compiler-owned Blueprint Variable IR to add_blueprint_member_variables for ensure-only member batches, or blueprint_variable_batch for mixed member/default/local variable ops; member variable properties/defaults execute through BlueprintVariableService, while local variable methods remain implementation-pending.',
  },
  capability_catalog: {
    source_root: 'Resources/v0.3.6/DoneImplementaion',
    agent_default_surface: [
      'blueprinthelper_read_task_context',
      'blueprinthelper_preview_task',
      'blueprinthelper_execute_task',
      'blueprinthelper_get_task_result',
    ],
    task_runtime_clusters: [
      {
        cluster: 'graph_write',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'graph_write',
        runtime_adapter_operations: [
          'append_blueprint_graph',
          'replace_blueprint_graph',
          'patch_blueprint_graph',
          'merge_blueprint_graph',
        ],
        ue_commands: [
          'append_blueprint_graph',
          'replace_blueprint_graph',
          'patch_blueprint_graph',
          'merge_blueprint_graph',
        ],
        documents: [
          'BlueprintHelper_AppendBlueprintGraph_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_ReplaceBlueprintGraph_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_PatchBlueprintGraph_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_MergeBlueprintGraph_UE_CPP_Implementation_Plan_20260503.md',
        ],
        note: 'Custom Event entry ownership is expressed through blueprint_signature dependency steps; GraphWrite remains the body/node/link writer and is not a default Agent tool.',
      },
      {
        cluster: 'blueprint_signature',
        agent_exposure: 'taskplan_internal',
        taskplan_capability: 'blueprint_signature',
        runtime_adapter_operations: [
          'ensure_function',
          'ensure_custom_event',
        ],
        ue_commands: [
          'ensure_function',
          'ensure_custom_event',
        ],
        documents: [
          'BlueprintHelper_FunctionEventSignatureManagement_UE_CPP_Implementation_Plan_20260504.md',
        ],
      },
      {
        cluster: 'graph_cleanup_ownership',
        agent_exposure: 'taskplan_internal',
        runtime_adapter_operations: [
          'cleanup_blueprinthelper_block',
          'convert_block_to_user_owned',
          'rollback_cleanup_transaction',
        ],
        ue_commands: [
          'cleanup_blueprinthelper_block',
          'convert_block_to_user_owned',
          'rollback_cleanup_transaction',
        ],
        documents: [
          'BlueprintHelper_CleanupBlueprintHelperBlock_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_ConvertBlockToUserOwned_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_RollbackCleanupTransaction_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
      {
        cluster: 'blueprint_variables',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'blueprint_variable',
        runtime_adapter_operations: [
          'add_blueprint_member_variables',
        ],
        ue_commands: [
          'read_blueprint_member_variables',
          'add_blueprint_member_variable',
          'add_blueprint_member_variables',
          'set_blueprint_member_variable_properties',
          'remove_blueprint_member_variable',
          'remove_blueprint_member_variables',
          'read_blueprint_member_defaults',
          'set_blueprint_member_default',
          'set_blueprint_member_defaults',
          'read_blueprint_local_variables',
          'add_blueprint_local_variable',
          'add_blueprint_local_variables',
          'set_blueprint_local_variable_properties',
          'remove_blueprint_local_variable',
          'remove_blueprint_local_variables',
        ],
        documents: [
          'BlueprintHelper_BlueprintVariables_Defaults_LocalVariables_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
      {
        cluster: 'asset_factory',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'asset_factory',
        runtime_adapter_operations: [
          'create_asset',
        ],
        ue_commands: [
          'create_asset',
        ],
        documents: [
          'BlueprintHelper_AssetFactory_UE_FieldMapping_20260502.md',
        ],
      },
      {
        cluster: 'blueprint_component',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'blueprint_component',
        runtime_adapter_operations: [
          'add_component',
          'set_component_properties',
          'remove_component',
        ],
        ue_commands: [
          'read_components',
          'add_component',
          'set_component_property',
          'set_component_properties',
          'remove_component',
        ],
        documents: [
          'BlueprintHelper_BlueprintComponent_UE_FieldMapping_20260502.md',
        ],
      },
      {
        cluster: 'blueprint_class_settings',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'blueprint_class_settings',
        runtime_adapter_operations: [
          'add_implemented_interfaces',
          'remove_implemented_interfaces',
          'set_class_default_properties',
        ],
        ue_commands: [
          'read_class_settings',
          'add_implemented_interface',
          'add_implemented_interfaces',
          'remove_implemented_interface',
          'remove_implemented_interfaces',
          'set_class_default_property',
          'set_class_default_properties',
        ],
        documents: [
          'BlueprintHelper_BlueprintClassSettings_UE_FieldMapping_20260503.md',
        ],
      },
      {
        cluster: 'umg_widget_blueprint',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'umg_widget',
        runtime_adapter_operations: [
          'add_widget',
          'set_widget_property',
          'remove_widget',
        ],
        ue_commands: [
          'get_widget_tree',
          'add_widget',
          'remove_widget',
          'move_widget',
          'get_widget_properties',
          'set_widget_property',
        ],
        documents: [
          'BlueprintHelper_UMG_WidgetBlueprint_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
      {
        cluster: 'data_asset',
        agent_exposure: 'taskplan_internal',
        runtime_adapter_operations: [
          'read_data_asset',
          'set_data_asset_properties',
        ],
        ue_commands: [
          'read_data_asset',
          'set_data_asset_properties',
        ],
        documents: [
          'BlueprintHelper_DataAsset_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
      {
        cluster: 'data_table',
        agent_exposure: 'taskspec_only',
        taskplan_capability: 'data_table',
        runtime_adapter_operations: [
          'add_datatable_row',
          'update_datatable_row',
          'delete_datatable_row',
        ],
        ue_commands: [
          'get_data_table_rows',
          'add_data_table_row',
          'update_data_table_row',
          'delete_data_table_row',
        ],
        documents: [
          'BlueprintHelper_DataTable_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
      {
        cluster: 'compile_save',
        agent_exposure: 'taskplan_internal',
        runtime_adapter_operations: [
          'compile_blueprint_asset',
          'save_asset',
        ],
        ue_commands: [
          'compile_blueprint_asset',
          'save_asset',
        ],
        documents: [
          'BlueprintHelper_CompileBlueprintAsset_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_SaveAsset_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
    ],
    support_clusters: [
      {
        cluster: 'runtime_profile',
        agent_exposure: 'agent_read',
        ue_commands: ['get_runtime_profile'],
        documents: ['BlueprintHelper_RuntimeProfile_UE_CPP_Implementation_Plan_20260503.md'],
      },
      {
        cluster: 'diagnostics_discovery',
        agent_exposure: 'agent_read_or_debug',
        ue_commands: [
          'diagnostics',
          'asset_discovery',
          'editor_navigation',
          'debug_export',
          'internal_dependency_analysis',
          'project_context',
          'setup_state',
        ],
        documents: [
          'BlueprintHelper_Diagnostics_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_AssetDiscovery_EditorNavigation_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_DebugExport_LargePayload_UE_CPP_Implementation_Plan_20260503.md',
          'BlueprintHelper_InternalDependencyAnalysis_UE_ImplementationPlan_20260503.md',
          'BlueprintHelper_ProjectContext_SetupState_UE_CPP_Implementation_Plan_20260503.md',
        ],
      },
      {
        cluster: 'transaction_journal',
        agent_exposure: 'task_result_or_debug',
        ue_commands: ['get_transaction_journal', 'get_task_run_journal'],
        documents: ['BlueprintHelper_TransactionJournalQuery_UE_CPP_Implementation_Plan_20260503.md'],
      },
      {
        cluster: 'editor_lifecycle',
        agent_exposure: 'debug_or_risk_command',
        ue_commands: ['open_editor', 'close_editor'],
        documents: ['BlueprintHelper_EditorLifecycle_RiskCommand_UE_CPP_Implementation_Plan_20260503.md'],
      },
      {
        cluster: 'common_envelope',
        agent_exposure: 'protocol_internal',
        ue_commands: [],
        documents: ['BlueprintHelper_ToolResultBase_CommonEnvelope_UE_CPP_Implementation_Plan_20260503.md'],
      },
    ],
  },
  validation_policy: {
    task_spec_fields: ['should_compile', 'should_save'],
    task_plan_fields: ['should_compile', 'should_save'],
    forbidden_fields: ['compile', 'save'],
  },
  bridge_commands: {
    preview: 'preview_task_plan',
    execute: 'execute_task_plan',
    journal: 'get_task_run_journal',
  },
} as const;

export type TaskProtocolContract = typeof TASK_PROTOCOL_CONTRACT_V1;
