import type { CapabilityDescriptor } from './capability-descriptor.schema.js';

function descriptor(input: Omit<CapabilityDescriptor, 'schema'>): CapabilityDescriptor {
  return {
    schema: 'BlueprintHelper.CapabilityDescriptor.v1',
    ...input,
  };
}

const TASK_PREVIEW = { supported: true, required_for_execute: true } as const;
const READ_PREVIEW = { supported: false, required_for_execute: false } as const;
const DEBUG_PREVIEW = { supported: false, required_for_execute: false } as const;

export const CAPABILITY_DESCRIPTORS: readonly CapabilityDescriptor[] = [
  descriptor({
    id: 'graphwrite.execute',
    family: 'graphwrite',
    operation: 'execute',
    asset_kinds: ['blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'graphwrite_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'graphwrite_review_evidence',
      restore_adapter: 'graphwrite_snapshot_restore',
      surface_adapter: 'graph_panel',
    },
    debug: { projection_adapter: 'graphwrite_debug_projection' },
    read_context: { projection_adapter: 'blueprint_logic_projection', route_refs: ['blueprint.logic.flow'] },
    ui: { presenter_adapter: 'graph_panel_presenter', surface: 'graph_panel' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'asset_factory.create',
    family: 'asset_factory',
    operation: 'create',
    asset_kinds: ['blueprint', 'widget_blueprint', 'data_asset', 'data_table', 'structure', 'material'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'asset_factory_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'asset_factory_review_evidence',
      restore_adapter: 'asset_factory_restore',
      surface_adapter: 'asset_lifecycle',
    },
    debug: { projection_adapter: 'asset_factory_debug_projection' },
    read_context: { projection_adapter: 'asset_discovery_projection', route_refs: [] },
    ui: { presenter_adapter: 'asset_lifecycle_presenter', surface: 'final_review' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'blueprint_variables.edit',
    family: 'blueprint_variables',
    operation: 'edit',
    asset_kinds: ['blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'blueprint_variables_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'blueprint_variables_review_evidence',
      restore_adapter: 'blueprint_variables_restore',
      surface_adapter: 'my_blueprint',
    },
    debug: { projection_adapter: 'blueprint_variables_debug_projection' },
    read_context: { projection_adapter: 'blueprint_variable_projection', route_refs: ['blueprint.schema.variables'] },
    ui: { presenter_adapter: 'my_blueprint_presenter', surface: 'my_blueprint' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'blueprint_signature.edit',
    family: 'blueprint_signature',
    operation: 'edit',
    asset_kinds: ['blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'blueprint_signature_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'blueprint_signature_review_evidence',
      restore_adapter: 'blueprint_signature_restore',
      surface_adapter: 'my_blueprint',
    },
    debug: { projection_adapter: 'blueprint_signature_debug_projection' },
    read_context: { projection_adapter: 'blueprint_logic_projection', route_refs: ['blueprint.logic.flow'] },
    ui: { presenter_adapter: 'my_blueprint_presenter', surface: 'my_blueprint' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'blueprint_component.edit',
    family: 'blueprint_component',
    operation: 'edit',
    asset_kinds: ['blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'blueprint_component_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'blueprint_component_review_evidence',
      restore_adapter: 'blueprint_component_restore',
      surface_adapter: 'components',
    },
    debug: { projection_adapter: 'blueprint_component_debug_projection' },
    read_context: { projection_adapter: 'blueprint_component_projection', route_refs: ['blueprint.structure.components'] },
    ui: { presenter_adapter: 'components_presenter', surface: 'components' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'class_settings.edit',
    family: 'class_settings',
    operation: 'edit',
    asset_kinds: ['blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'class_settings_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'class_settings_review_evidence',
      restore_adapter: 'class_settings_restore',
      surface_adapter: 'details',
    },
    debug: { projection_adapter: 'class_settings_debug_projection' },
    read_context: { projection_adapter: 'blueprint_class_settings_projection', route_refs: ['blueprint.class_settings'] },
    ui: { presenter_adapter: 'details_presenter', surface: 'details' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'umg_widget_tree.edit',
    family: 'umg_widget_tree',
    operation: 'edit',
    asset_kinds: ['widget_blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'umg_widget_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'widget_tree_review_evidence',
      restore_adapter: 'widget_tree_restore',
      surface_adapter: 'widget_tree',
    },
    debug: { projection_adapter: 'widget_tree_debug_projection' },
    read_context: { projection_adapter: 'widget_tree_projection', route_refs: ['widget.structure.tree_json'] },
    ui: { presenter_adapter: 'widget_tree_presenter', surface: 'widget_tree' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'data_asset.object_properties.edit',
    family: 'object_property',
    operation: 'edit',
    asset_kinds: ['data_asset', 'blueprint'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'object_property_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'object_property_review_evidence',
      restore_adapter: 'object_property_restore',
      surface_adapter: 'data_asset',
    },
    debug: { projection_adapter: 'object_property_debug_projection' },
    read_context: { projection_adapter: 'object_property_projection', route_refs: ['data_asset.properties'] },
    ui: { presenter_adapter: 'data_asset_presenter', surface: 'data_asset' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'data_table.rows.edit',
    family: 'data_table',
    operation: 'edit',
    asset_kinds: ['data_table'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'data_table_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'data_table_review_evidence',
      restore_adapter: 'data_table_restore',
      surface_adapter: 'data_table',
    },
    debug: { projection_adapter: 'data_table_debug_projection' },
    read_context: { projection_adapter: 'data_table_projection', route_refs: ['data_table.rows'] },
    ui: { presenter_adapter: 'data_table_presenter', surface: 'data_table' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'struct.fields.edit',
    family: 'struct',
    operation: 'edit',
    asset_kinds: ['structure'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'struct_runtime_adapter', status: 'planned' },
    review: {
      evidence_adapter: 'struct_review_evidence',
      restore_adapter: 'struct_restore',
      surface_adapter: 'struct',
    },
    debug: { projection_adapter: 'struct_debug_projection' },
    read_context: { projection_adapter: 'struct_projection', route_refs: ['struct.fields'] },
    ui: { presenter_adapter: 'struct_presenter', surface: 'struct' },
    safety: { risk: 'high', reserved_only: true, write_approval_required: true },
  }),
  descriptor({
    id: 'material_graph.edit',
    family: 'material_graph',
    operation: 'edit',
    asset_kinds: ['material'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'material_graph_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'material_graph_review_evidence',
      restore_adapter: 'material_graph_restore',
      surface_adapter: 'material_graph',
    },
    debug: { projection_adapter: 'material_graph_debug_projection' },
    read_context: { projection_adapter: 'material_graph_projection', route_refs: ['material.logic.flow', 'material.logic.json'] },
    ui: { presenter_adapter: 'material_graph_presenter', surface: 'material_graph' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
  descriptor({
    id: 'debug_case.export_summary',
    family: 'debug_case',
    operation: 'export_summary',
    asset_kinds: ['debug_case'],
    routing: { cli_command: 'blueprinthelper_export_debug_bundle', bridge_command: 'export_debug_bundle', handler_id: 'debug_case_export' },
    preview: DEBUG_PREVIEW,
    runtime: { adapter_id: 'debug_case_export_runtime_adapter', status: 'active' },
    review: {},
    debug: { export_projection: 'debug_case_export_projection' },
    read_context: { route_refs: [] },
    ui: {},
    safety: { risk: 'low', reserved_only: false, write_approval_required: false },
  }),
  descriptor({
    id: 'material_instance.edit',
    family: 'material_instance',
    operation: 'edit',
    asset_kinds: ['material_instance_constant'],
    routing: { cli_command: 'task execute', bridge_command: 'execute_task_plan', handler_id: 'task_runtime' },
    preview: TASK_PREVIEW,
    runtime: { adapter_id: 'material_instance_runtime_adapter', status: 'active' },
    review: {
      evidence_adapter: 'material_instance_review_evidence',
      restore_adapter: 'material_instance_restore',
      surface_adapter: 'material_instance',
    },
    debug: { projection_adapter: 'material_instance_debug_projection' },
    read_context: { projection_adapter: 'material_instance_projection', route_refs: [] },
    ui: { presenter_adapter: 'material_instance_presenter', surface: 'material_instance' },
    safety: { risk: 'high', reserved_only: false, write_approval_required: true },
  }),
] as const;
