import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { listCapabilityDescriptors } from './capability-descriptor-registry.js';

const THIS_DIR = path.dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = path.resolve(THIS_DIR, '../../../../..');
const HEADER_PATH = path.join(
  PLUGIN_ROOT,
  'BlueprintHelper/Source/BlueprintHelper/Public/Runtime/Capabilities/BlueprintHelperGeneratedCapabilityRegistry.h',
);
const SOURCE_PATH = path.join(
  PLUGIN_ROOT,
  'BlueprintHelper/Source/BlueprintHelper/Private/Runtime/Capabilities/BlueprintHelperGeneratedCapabilityRegistry.cpp',
);

const descriptors = listCapabilityDescriptors()
  .slice()
  .sort((left, right) => left.id.localeCompare(right.id));

mkdirSync(path.dirname(HEADER_PATH), { recursive: true });
mkdirSync(path.dirname(SOURCE_PATH), { recursive: true });

writeFileSync(HEADER_PATH, buildHeader(), 'utf8');
writeFileSync(SOURCE_PATH, buildSource(), 'utf8');

function buildHeader(): string {
  return `// Generated by AgentFaceService/task-core/src/tool-surface/capabilities/generate-ue-capability-registry.ts. Do not edit manually.

#pragma once

#include "CoreMinimal.h"
#include "Containers/ArrayView.h"
#include "Runtime/Capabilities/BlueprintHelperCapabilityDescriptorTypes.h"

struct FBlueprintHelperGeneratedCapabilityDescriptor
{
\tconst TCHAR* Id = TEXT("");
\tconst TCHAR* Family = TEXT("");
\tconst TCHAR* Operation = TEXT("");
\tconst TCHAR* RoutingCliCommand = TEXT("");
\tconst TCHAR* RoutingBridgeCommand = TEXT("");
\tconst TCHAR* RoutingHandlerId = TEXT("");
\tconst TCHAR* RuntimeAdapterId = TEXT("");
\tconst TCHAR* RuntimeStatus = TEXT("");
\tconst TCHAR* SafetyRisk = TEXT("");
\tbool bReservedOnly = false;
\tbool bWriteApprovalRequired = false;
};

class BLUEPRINTHELPER_API FBlueprintHelperGeneratedCapabilityRegistry
{
public:
\tstatic TConstArrayView<FBlueprintHelperGeneratedCapabilityDescriptor> ListDescriptors();
\tstatic const FBlueprintHelperGeneratedCapabilityDescriptor* FindById(const FString& Id);
\tstatic bool IsDescriptorAgentVisible(
\t\tconst FBlueprintHelperGeneratedCapabilityDescriptor& Descriptor,
\t\tconst FBlueprintHelperCapabilityDescriptorRuntimeState& RuntimeState);
};
`;
}

function buildSource(): string {
  const rows = descriptors.map((descriptor) =>
    `\t{ TEXT("${escapeCpp(descriptor.id)}"), TEXT("${escapeCpp(descriptor.family)}"), TEXT("${escapeCpp(descriptor.operation)}"), TEXT("${escapeCpp(descriptor.routing.cli_command)}"), TEXT("${escapeCpp(descriptor.routing.bridge_command ?? '')}"), TEXT("${escapeCpp(descriptor.routing.handler_id)}"), TEXT("${escapeCpp(descriptor.runtime.adapter_id)}"), TEXT("${escapeCpp(descriptor.runtime.status)}"), TEXT("${escapeCpp(descriptor.safety.risk)}"), ${descriptor.safety.reserved_only ? 'true' : 'false'}, ${descriptor.safety.write_approval_required ? 'true' : 'false'} },`
  ).join('\n');
  return `// Generated by AgentFaceService/task-core/src/tool-surface/capabilities/generate-ue-capability-registry.ts. Do not edit manually.

#include "Runtime/Capabilities/BlueprintHelperGeneratedCapabilityRegistry.h"

static const FBlueprintHelperGeneratedCapabilityDescriptor GBlueprintHelperGeneratedCapabilityDescriptors[] =
{
${rows}
};

TConstArrayView<FBlueprintHelperGeneratedCapabilityDescriptor> FBlueprintHelperGeneratedCapabilityRegistry::ListDescriptors()
{
\treturn MakeArrayView(GBlueprintHelperGeneratedCapabilityDescriptors);
}

const FBlueprintHelperGeneratedCapabilityDescriptor* FBlueprintHelperGeneratedCapabilityRegistry::FindById(const FString& Id)
{
\tfor (const FBlueprintHelperGeneratedCapabilityDescriptor& Descriptor : GBlueprintHelperGeneratedCapabilityDescriptors)
\t{
\t\tif (Id == Descriptor.Id)
\t\t{
\t\t\treturn &Descriptor;
\t\t}
\t}
\treturn nullptr;
}

bool FBlueprintHelperGeneratedCapabilityRegistry::IsDescriptorAgentVisible(
\tconst FBlueprintHelperGeneratedCapabilityDescriptor& Descriptor,
\tconst FBlueprintHelperCapabilityDescriptorRuntimeState& RuntimeState)
{
\tif (Descriptor.bReservedOnly)
\t{
\t\treturn false;
\t}
\tif (!FString(Descriptor.RuntimeStatus).Equals(TEXT("active"), ESearchCase::IgnoreCase))
\t{
\t\treturn false;
\t}
\tif (!RuntimeState.RegisteredRuntimeAdapterIds.Contains(FString(Descriptor.RuntimeAdapterId)))
\t{
\t\treturn false;
\t}
\tif (Descriptor.bWriteApprovalRequired && !RuntimeState.bAllowWriteCapabilities)
\t{
\t\treturn false;
\t}
\tif (FString(Descriptor.SafetyRisk).Equals(TEXT("high"), ESearchCase::IgnoreCase) &&
\t\t!RuntimeState.bAllowHighRiskCapabilities)
\t{
\t\treturn false;
\t}
\treturn true;
}
`;
}

function escapeCpp(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll('"', '\\"');
}
