// Generated by AgentFaceService/task-core/src/tool-surface/capabilities/generate-ue-capability-registry.ts. Do not edit manually.

#include "Runtime/Capabilities/BlueprintHelperGeneratedCapabilityRegistry.h"

static const FBlueprintHelperGeneratedCapabilityDescriptor GBlueprintHelperGeneratedCapabilityDescriptors[] =
{
	{ TEXT("asset_factory.create"), TEXT("asset_factory"), TEXT("create"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("asset_factory_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("blueprint_component.edit"), TEXT("blueprint_component"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("blueprint_component_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("blueprint_signature.edit"), TEXT("blueprint_signature"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("blueprint_signature_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("blueprint_variables.edit"), TEXT("blueprint_variables"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("blueprint_variables_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("class_settings.edit"), TEXT("class_settings"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("class_settings_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("data_asset.object_properties.edit"), TEXT("object_property"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("object_property_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("data_table.rows.edit"), TEXT("data_table"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("data_table_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("debug_case.export_summary"), TEXT("debug_case"), TEXT("export_summary"), TEXT("blueprinthelper_export_debug_bundle"), TEXT("export_debug_bundle"), TEXT("debug_case_export"), TEXT("debug_case_export_runtime_adapter"), TEXT("active"), TEXT("low"), false, false },
	{ TEXT("graphwrite.execute"), TEXT("graphwrite"), TEXT("execute"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("graphwrite_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("material_graph.edit"), TEXT("material_graph"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("material_graph_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("material_instance.edit"), TEXT("material_instance"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("material_instance_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
	{ TEXT("struct.fields.edit"), TEXT("struct"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("struct_runtime_adapter"), TEXT("planned"), TEXT("high"), true, true },
	{ TEXT("umg_widget_tree.edit"), TEXT("umg_widget_tree"), TEXT("edit"), TEXT("task execute"), TEXT("execute_task_plan"), TEXT("task_runtime"), TEXT("umg_widget_runtime_adapter"), TEXT("active"), TEXT("high"), false, true },
};

TConstArrayView<FBlueprintHelperGeneratedCapabilityDescriptor> FBlueprintHelperGeneratedCapabilityRegistry::ListDescriptors()
{
	return MakeArrayView(GBlueprintHelperGeneratedCapabilityDescriptors);
}

const FBlueprintHelperGeneratedCapabilityDescriptor* FBlueprintHelperGeneratedCapabilityRegistry::FindById(const FString& Id)
{
	for (const FBlueprintHelperGeneratedCapabilityDescriptor& Descriptor : GBlueprintHelperGeneratedCapabilityDescriptors)
	{
		if (Id == Descriptor.Id)
		{
			return &Descriptor;
		}
	}
	return nullptr;
}

bool FBlueprintHelperGeneratedCapabilityRegistry::IsDescriptorAgentVisible(
	const FBlueprintHelperGeneratedCapabilityDescriptor& Descriptor,
	const FBlueprintHelperCapabilityDescriptorRuntimeState& RuntimeState)
{
	if (Descriptor.bReservedOnly)
	{
		return false;
	}
	if (!FString(Descriptor.RuntimeStatus).Equals(TEXT("active"), ESearchCase::IgnoreCase))
	{
		return false;
	}
	if (!RuntimeState.RegisteredRuntimeAdapterIds.Contains(FString(Descriptor.RuntimeAdapterId)))
	{
		return false;
	}
	if (Descriptor.bWriteApprovalRequired && !RuntimeState.bAllowWriteCapabilities)
	{
		return false;
	}
	if (FString(Descriptor.SafetyRisk).Equals(TEXT("high"), ESearchCase::IgnoreCase) &&
		!RuntimeState.bAllowHighRiskCapabilities)
	{
		return false;
	}
	return true;
}
