// BlueprintHelper Service Layer — LogicMD Read Service 实现

#include "Services/BlueprintHelperLogicMdReadService.h"
#include "Services/BlueprintHelperLogicMdTypes.h"
#include "Services/BlueprintHelperLogicGroupBuilder.h"
#include "Services/BlueprintHelperToolResultTypes.h"
#include "Services/BlueprintHelperServiceTypes.h"
#include "Services/BlueprintHelperExportService.h"
#include "Services/BlueprintHelperGraphResolver.h"
#include "Services/BlueprintHelperLogicProcessor.h"
#include "BlueprintHelper.h"

FBlueprintHelperLogicMdReadService::FBlueprintHelperLogicMdReadService() = default;

FBlueprintHelperLogicMdData FBlueprintHelperLogicMdReadService::ReadLogicMd(const FBlueprintHelperTargetRef& Target) const
{
	FBlueprintHelperLogicMdData Data;

	// 确定 scope
	const EBlueprintHelperLogicScope Scope = TargetTypeToScope(Target.TargetType);
	Data.Scope = Scope;

	// 准备 ExportRequest
	FBlueprintHelperExportRequest ExportReq;
	ExportReq.Target.BlueprintPath = Target.AssetPath;
	if (!Target.Graph.IsEmpty())
	{
		ExportReq.Target.GraphName = Target.Graph;
	}
	ExportReq.Scope = ScopeToExportScope(Scope);

	// 使用模块的 ExportService 导出 Raw JSON
	const FBlueprintHelperModule& Module = FBlueprintHelperModule::Get();
	const FBlueprintHelperExportResult ExportResult = Module.GetExportService().Export(ExportReq);

	if (!ExportResult.bSuccess)
	{
		// 导出失败，返回空 Markdown 标记失败
		Data.Markdown = TEXT("(导出失败)");
		Data.bImportable = false;
		return Data;
	}

	// 通过 LogicProcessor 生成 Markdown
	FBlueprintHelperLogicOptions LogicOptions;
	LogicOptions.Format = EBlueprintHelperLogicOutputFormat::Markdown;
	LogicOptions.DetailLevel = EBlueprintHelperLogicDetailLevel::Normal;
	LogicOptions.bIncludeDataDependencies = true;
	LogicOptions.bIncludeOrphanNodes = true;
	LogicOptions.bIncludeNodeIds = false;
	LogicOptions.bIncludePositions = false;
	LogicOptions.bIncludeRawNodeTypes = false;

	const FBlueprintHelperLogicResult LogicResult =
		FBlueprintHelperLogicProcessor::ProcessRawJsonObject(ExportResult.JsonObject, LogicOptions);

	if (!LogicResult.bSuccess)
	{
		Data.Markdown = TEXT("(Logic Processor 失败)");
		Data.bImportable = false;
		return Data;
	}

	// 填充 Markdown
	Data.Markdown = LogicResult.OutputText;
	Data.bImportable = false;

	// ─── 构建 scope 收敛的 stats ───
	FBlueprintHelperLogicMdStats& Stats = Data.Stats;
	Stats.Nodes = LogicResult.NodeCount;
	Stats.ExecLinks = LogicResult.ExecLinkCount;
	Stats.DataLinks = LogicResult.DataLinkCount;
	Stats.OrphanNodes = LogicResult.OrphanNodeCount;

	// 多入口 scope 下使用 group builder 构建分组并设置 grouped
	const bool bIsMultiEntry = FBlueprintHelperLogicGroupBuilder::IsMultiEntryScope(Scope);
	if (bIsMultiEntry)
	{
		const FString GraphName = Target.Graph.IsEmpty() ? TEXT("EventGraph") : Target.Graph;
		const FBlueprintHelperLogicJsonPayload GroupPayload = GroupBuilder.BuildGroups(
			ExportResult.JsonObject, Target.AssetPath, GraphName, Scope);
		Stats.Groups = GroupPayload.Groups.Num();
		Data.bGrouped = true;
		// Markdown is already generated by LogicProcessor, we just add grouped flag
	}

	switch (Scope)
	{
	case EBlueprintHelperLogicScope::Blueprint:
		Stats.Graphs = 1;
		Stats.Functions = 0;
		Stats.Events = LogicResult.EntryPointCount;
		Data.bGrouped = true;
		break;

	case EBlueprintHelperLogicScope::TargetGraph:
		Stats.Events = LogicResult.EntryPointCount;
		Data.bGrouped = true;
		break;

	case EBlueprintHelperLogicScope::TargetFunction:
	case EBlueprintHelperLogicScope::TargetEvent:
	case EBlueprintHelperLogicScope::TargetCustomEvent:
	case EBlueprintHelperLogicScope::TargetBlock:
		// 只返回基础 node/exec/data/orphan 统计
		break;

	case EBlueprintHelperLogicScope::MultiTarget:
		Stats.Targets = 1;
		break;
	}

	return Data;
}

EBlueprintHelperLogicScope FBlueprintHelperLogicMdReadService::TargetTypeToScope(EBlueprintHelperTargetType Type)
{
	switch (Type)
	{
	case EBlueprintHelperTargetType::Blueprint:   return EBlueprintHelperLogicScope::Blueprint;
	case EBlueprintHelperTargetType::Graph:        return EBlueprintHelperLogicScope::TargetGraph;
	case EBlueprintHelperTargetType::Function:     return EBlueprintHelperLogicScope::TargetFunction;
	case EBlueprintHelperTargetType::Event:        return EBlueprintHelperLogicScope::TargetEvent;
	case EBlueprintHelperTargetType::CustomEvent:  return EBlueprintHelperLogicScope::TargetCustomEvent;
	case EBlueprintHelperTargetType::Block:        return EBlueprintHelperLogicScope::TargetBlock;
	default:                                       return EBlueprintHelperLogicScope::TargetGraph;
	}
}

EBlueprintHelperExportScope FBlueprintHelperLogicMdReadService::ScopeToExportScope(EBlueprintHelperLogicScope Scope)
{
	switch (Scope)
	{
	case EBlueprintHelperLogicScope::Blueprint:
		return EBlueprintHelperExportScope::FullBlueprint;
	case EBlueprintHelperLogicScope::TargetGraph:
	case EBlueprintHelperLogicScope::TargetFunction:
	case EBlueprintHelperLogicScope::TargetEvent:
	case EBlueprintHelperLogicScope::TargetCustomEvent:
	case EBlueprintHelperLogicScope::TargetBlock:
	default:
		return EBlueprintHelperExportScope::SingleGraph;
	}
}
