// Generated by AgentFaceService/task-core/src/tool-surface/capabilities/generate-ue-capability-registry.ts. Do not edit manually.

#pragma once

#include "CoreMinimal.h"
#include "Containers/ArrayView.h"
#include "Runtime/Capabilities/BlueprintHelperCapabilityDescriptorTypes.h"

struct FBlueprintHelperGeneratedCapabilityDescriptor
{
	const TCHAR* Id = TEXT("");
	const TCHAR* Family = TEXT("");
	const TCHAR* Operation = TEXT("");
	const TCHAR* RoutingCliCommand = TEXT("");
	const TCHAR* RoutingBridgeCommand = TEXT("");
	const TCHAR* RoutingHandlerId = TEXT("");
	const TCHAR* RoutingRouteCluster = TEXT("");
	const TCHAR* RoutingSourceId = TEXT("");
	const TCHAR* RoutingPolicyId = TEXT("");
	bool bRoutingAgentVisible = false;
	bool bRoutingRequiresGameThread = true;
	const TCHAR* RuntimeAdapterId = TEXT("");
	const TCHAR* RuntimeStatus = TEXT("");
	const TCHAR* SafetyRisk = TEXT("");
	bool bReservedOnly = false;
	bool bWriteApprovalRequired = false;
};

class BLUEPRINTHELPER_API FBlueprintHelperGeneratedCapabilityRegistry
{
public:
	static TConstArrayView<FBlueprintHelperGeneratedCapabilityDescriptor> ListDescriptors();
	static const FBlueprintHelperGeneratedCapabilityDescriptor* FindById(const FString& Id);
	static bool IsDescriptorAgentVisible(
		const FBlueprintHelperGeneratedCapabilityDescriptor& Descriptor,
		const FBlueprintHelperCapabilityDescriptorRuntimeState& RuntimeState);
};
